route:
  group_by: ['homiesapp']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
  - name: 'web.hook'
    webhook_configs:
        - url: https://webhook.site/93de1bc6-9263-452c-a5b1-29f1606cee97